name: Deploy Para Ambiente de Producao 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório github
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configurar Credenciais da AWS
      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Altere para a região do seu Lightsail e ECR

      # Logar no Amazon ECR
      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com

      # Construir a imagem Docker
      - name: Build da imagem
        run: |
          docker build -t meu-app-stage .

      # Tag da imagem para enviar ao ECR
      - name: Tag da imagem para o ECR
        run: |
          docker tag meu-app-stage:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/meu-app-stage:latest

      # Push da imagem para o ECR
      - name: Enviar a Imagem para o Amazon ECR
        run: |
          docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/meu-app-stage:latest
      
      # Configurar SSH e Deploy na Instância Lightsail
      - name: Deploy na Instância Lightsail via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            sudo docker login --username AWS --password $(aws ecr get-login-password --region us-east-1) 123456789012.dkr.ecr.us-east-1.amazonaws.com
            sudo docker pull 123456789012.dkr.ecr.us-east-1.amazonaws.com/meu-app-stage:latest
            sudo docker stop meu-app || true
            sudo docker rm meu-app || true
            sudo docker run -d --name meu-app -p 80:3000 123456789012.dkr.ecr.us-east-1.amazonaws.com/meu-app-stage:latest
