name: Deploy Para Ambiente de Producao

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do reposit처rio github
      - name: Checkout do c처digo
        uses: actions/checkout@v3

      - name: Debug secrets
        run: echo "AWS_REGION is ${{ secrets.AWS_REGION }}"

      # Configurar Credenciais da AWS
      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Logar no Amazon ECR
      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin 316429278885.dkr.ecr.us-east-1.amazonaws.com

      # Construir a imagem Docker
      - name: Build da imagem
        run: |
          docker build -t meu-app-prod .

      # Tag da imagem para enviar ao ECR
      - name: Tag da imagem para o ECR
        run: |
          docker tag app-form-web:latest 316429278885.dkr.ecr.us-east-1.amazonaws.com/app-form-web

      # Push da imagem para o ECR
      - name: Enviar a Imagem para o Amazon ECR
        run: |
          docker push 316429278885.dkr.ecr.us-east-1.amazonaws.com/app-form-web:latest

      # Deploy na Inst창ncia EC2 via SSH
      - name: Deploy na Inst창ncia EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo docker login --username AWS --password $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) 123456789012.dkr.ecr.us-east-1.amazonaws.com
            sudo docker pull 123456789012.dkr.ecr.us-east-1.amazonaws.com/meu-app-prod:latest
            sudo docker stop meu-app || true
            sudo docker rm meu-app || true
            sudo docker run -d --name meu-app -p 80:3000 123456789012.dkr.ecr.us-east-1.amazonaws.com/meu-app-prod:latest
